### ISSUE TITLE
How can I make this work?

### ISSUE THREAD

**Issue by vladimircezar** [mmckegg/json-query#18]
So, this is my JSON:
```
{ 
  '-KIEUvGDw2Mm36W_EM68': { 
        author: 'Sean Bean',
        hearts: 3,
        text: '006 was such an interesting character and the film really explored his friendship with Bond and how it all went wrong, so it was a very personal journey for both characters.'
  }
  '-KIEUvGJP3qMC3p5_-pZ': { 
        author: 'Rosa DeLauro',
        hearts: 2,
        text: '1 month ago the American people stopped to remember the third anniversary of the beginning of the Iraq war. We thought first and foremost of the selflessness, patriotism and heroism by our troops, our National Guard and Reserves.'
  },
  '-KIEUvGJP3qMC3p5_-p_': { 
        author: 'Bo Derek',
        hearts: 4,
        text: '10\' was amazing! I had no career before \'10\' and then all of a sudden I was able to do pretty much whatever I was able to do in the business.'
  }
}
How do I get all objects with 3 or more hearts? Or, the objects with authors starting with "B"?
I tried everything but I.m stuck in the keys (E.g. '-KIEUvGJP3qMC3p5_-pZ').

Any help would be enormously appreciated.

**Comment by mmckegg** [comment]
This didn't use to be possible, but is now supported since version **2.0.0**. 

```js
jsonQuery('[*][*hearts>=3]', {data: data})
```

To match "starts with" you can use regular expressions:

```js
jsonQuery('[*][*author~/^B/]', {data: data, allowRegexp: true})
```

If you need multiple conditions use boolean logic:

```js
jsonQuery('[*][* hearts>=3 & author~/^B/]', {data: data, allowRegexp: true})
```

By the way, the `[*]` flattens the object into an array just containing values.

**Comment by vladimircezar** [comment]
Thank you so much! Really appreciated.

**Comment by vladimircezar** [comment]
Still does not work. When I try to do what you recommend, I get this error:

TypeError: Cannot read property 'slice' of undefined

**Comment by mmckegg** [comment]
Can you send me an example of code that throws this error?

**Comment by vladimircezar** [comment]
````
data: {
 '-KIiI017ZHO4pDSKoPli': 
   { author: 'Sean Bean',
     hearts: 3},
  '-KIiI01AvL2M-9LLkPjN': 
   { author: 'Rosa DeLauro',
     hearts: 2},
  '-KIiI01BiBeO9tzDGl4G': 
   { author: 'Bo Derek',
     hearts: 4},
  '-KIiI01BiBeO9tzDGl4H': 
   { author: 'Billy Bush',
     hearts: 5},
  '-KIiI01CHVr6l_YGEV3Z': 
   { author: 'Doc Hastings',
     hearts: 3}
 }
````
Here is the code (authorParam="Derek"):
````    
var queryResults = jsonQuery(`[*][*author~/${authorParam}/i]`, {
                data: objects,
                allowRegexp: true
            });
            console.log(queryResults);
````
And the stack:
````
TypeError: Cannot read property 'slice' of undefined
    at tokenizeSelect (........../node_modules/json-query/lib/tokenize.js:172:17)
    at Object.handlers.select (................/node_modules/json-query/lib/tokenize.js:52:14)
    at handleBuffer (................
    at module.exports (................................/node_modules/json-query/lib/tokenize.js:123:9)
    at jsonQuery (..................................node_modules/json-query/index.js:16:29)
    at ...................................app.js:82:32
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by mmckegg** [comment]
Seems to be working for me. Are you using the latest version of json-query? (v2.1.0) 

This is the code I'm using:

```js
var data = {
   '-KIiI017ZHO4pDSKoPli':
     { author: 'Sean Bean',
       hearts: 3},
    '-KIiI01AvL2M-9LLkPjN':
     { author: 'Rosa DeLauro',
       hearts: 2},
    '-KIiI01BiBeO9tzDGl4G':
     { author: 'Bo Derek',
       hearts: 4},
    '-KIiI01BiBeO9tzDGl4H':
     { author: 'Billy Bush',
       hearts: 5},
    '-KIiI01CHVr6l_YGEV3Z':
     { author: 'Doc Hastings',
       hearts: 3}
}

var authorParam = "Derek";
var queryResults = jsonQuery(`[*][*author~/${authorParam}/i]`, {
    data: data,
    allowRegexp: true
}).value;

console.log(queryResults);
```

**Comment by mmckegg** [comment]
Also as of v2.1.0, you no longer need to use a regexp for matching includes. This will now work too:

```js
var authorParam = "Derek";
var queryResults = jsonQuery(`[*][*author~${authorParam}]`, {
    data: data
}).value;
```

Also to be safe (instead of just injecting stuff into queries), you can use the built in param escaping:

```js
var authorParam = "Derek";
var queryResults = jsonQuery(["[*][*author~?]", authorParam], {
    data: data
}).value;
```
